### PR TITLE
Add home/personal logic

### PR DESCRIPTION
**Pull request by eduzatoni**

### CODE REVIEW

**Comment by biancalui-emarsys** [comment]
I tried to download and build the project, got errors in both iOS and Android projects.

Screenshot 2020-11-09 at 12 10 36 PM
Screenshot 2020-11-09 at 12 11 35 PM

**Comment by biancalui-emarsys** [comment]
iOS:
After adding back package-lock.json and use npm install (no update), iOS sample project can be built.
Tested OK using HOME / PERSONAL logic, and with variants.

**Comment by biancalui-emarsys** [comment]
Sorry that I accidentally clicked the Close PR button...
Will need to create another PR after the Android change.
Sorry again and thanks a lot. 🙇🏻‍♂️

**Comment by tjg1** [comment]
LGTM

**Review by tjg1 — APPROVED** [review]

**Pull request merged**
